### ISSUE TITLE
zoomYLabels function issue

### ISSUE THREAD

**Issue by tobiw777** [vasturiano/timelines-chart#83]
Hi!
Thanks for a great timeline chart lib!
During my implementation of your lib I found some troubleshooting issue with zoomYLabels function.
Due to doc I try to use it like that:
`.onLabelClick(function(label, group){	
     	chart.zoomYLabels([label, label]
})`
where chart is my TimeLine object
In result I get error from vo function:

> timelines-chart.min.js:5 Uncaught TypeError: Cannot read property 'split' of undefined
    at Object.vo (timelines-chart.min.js:5)
    at r (timelines-chart.min.js:5)
    at Function.zoomYLabels (timelines-chart.min.js:5)
    at Function.Object.keys.forEach.o.<computed> [as zoomYLabels] (timelines-chart.min.js:2)
    at Object.onLabelClick (index.pl?Action=AgentITSMConfigItemZoom;ConfigItemID=5:977)
    at SVGTextElement.<anonymous> (timelines-chart.min.js:5)
    at SVGTextElement.<anonymous> (timelines-chart.min.js:2)

**Comment by boardend** [comment]
I’ve just noticed the same issue after upgrading from 2.10.0 to 2.11.1 (with d3-selection 2.0.0).

- **Uncaught TypeError: e.split is not a function**
  - at SVGTextElement.<anonymous> (timelines-chart.module.js:971)
  - at SVGTextElement.<anonymous> (on.js:3)

see [2.11.1: **src/timelines.js**#L899](https://github.com/vasturiano/timelines-chart/blob/v2.11.1/)

Will stay on 2.10.0 for the moment…
